# Generated by Django 4.0.2 on 2022-03-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('balance', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
