# Generated by Django 4.0.2 on 2022-03-10 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasxpagarapp', '0002_alter_proveedor_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDocumento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.PositiveIntegerField()),
                ('fechaDocumento', models.DateField()),
                ('monto', models.PositiveIntegerField()),
                ('fechaRegistro', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentasxpagarapp.proveedor')),
            ],
        ),
    ]
