# Generated by Django 4.0.2 on 2022-03-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasxpagarapp', '0004_entradadocumento_numerodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadocumento',
            name='proveedor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
