# Generated by Django 4.0.2 on 2022-03-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasxpagarapp', '0005_alter_entradadocumento_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadocumento',
            name='fechaDocumento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entradadocumento',
            name='fechaRegistro',
            field=models.DateField(),
        ),
    ]
