# Generated by Django 4.0.2 on 2022-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasxpagarapp', '0006_alter_entradadocumento_fechadocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadocumento',
            name='estado',
            field=models.CharField(default='', max_length=10),
        ),
    ]
