# Generated by Django 4.0.2 on 2022-04-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasxpagarapp', '0008_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadocumento',
            name='asiento_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
