# Generated by Django 4.0.2 on 2022-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasxpagarapp', '0009_entradadocumento_asiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadocumento',
            name='estado',
            field=models.CharField(default='', max_length=20),
        ),
    ]
